{% set name = "QDarkStyle" %}
{% set version = "3.0.2" %}
{% set sha256 = "55d149cf5f40ee297397f1818e091118cefb855a4a9c5c38566c47acd2d8c7ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - qdarkstyle=qdarkstyle.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - helpdev >=0.6.2
    - pyqt >=5
    - qtpy
    - qtsass

test:
  imports:
    - qdarkstyle
    - qdarkstyle.utils

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Python and Qt applications
