{% set name = "QDarkStyle" %}
{% set version = "2.8.1" %}
{% set sha256 = "d53b0120bddd9e3efba9801731e22ef86ed798bb5fc6a802f5f7bb32dedf0321" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - qdarkstyle=qdarkstyle.__main__:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - helpdev >=0.6.2
    - pyqt >=5

test:
  imports:
    - qdarkstyle
    - qdarkstyle.utils

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A dark stylesheet for Python and Qt applications

